# Generated by Django 2.0.2 on 2018-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plog',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
