# Generated by Django 2.0.2 on 2018-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
